### ISSUE TITLE
Release of 1.0 version and survey

### ISSUE THREAD

**Issue by sarahsba** [codefordurham/school-navigator#127]
What is our timeline for finishing the 1.0 version and releasing it for feedback?  Should I start teeing up a survey and putting together a list of outreach channels?  Let me know if there are specific questions you want to include.  I will plan to ask for feedback on the current version and for input on additional features.  I'll reference the survey that was started a while ago.  I'm planning to do it in Qualtrix because it has much better functionality than google forms.  If others want editing access, I can share my login details.  Let me know if you feel strongly that we should use google forms.

**Comment by lemanal** [comment]
I just updated the Phase I release date from May 26th to July 14th. We keep closing 5 tickets and adding 3. I don't have a preference for survey software.

**Comment by adamajm** [comment]
From Sarah: Here is a link to the School Navigator survey.  It'd be great if some of you could take a look at it tonight and let me know if any questions need to be added or changed.  Note that I haven't yet programmed the dependency of the sections so that you only see those that you've selected in the first question.

https://dukefuqua.qualtrics.com/jfe/preview/SV_3xfD0Xjs71CkDyt

**Comment by adamajm** [comment]
Hi Sue - can you take a read through this survey and give any comments on things confusing / additions / changes / etc. Thanks!

**Comment by lemanal** [comment]
Alpha is released. Survey is out.
