### ISSUE TITLE
132 TURNER RIDGE CIR geocodes to the wrong location

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#166]
School Navigator puts it on Ridge Road.

Google maps cannot find it

and Durham GIS places it near the Chatham county line off of 751 in a new development.

**Comment by jtf621** [comment]
another example of a bug that appears similar is 104 COLVARD WOODS WAY

School Navigator places it on WOODS ST

Google maps cannot find it

and Durham GIS places it near the Chatham county line off of 751 in a new development.

**Comment by lemanal** [comment]
I think it's possible that Durham GIS will have data about streets that aren't built before they're built whereas Google will not. Parents moving into new developments may need to use the drag/drop home feature rather than the text search box. Any argument to closing this as "won't fix"?

Only alternative I could think of would be to make our own geocoder using the county assessor data, but that feels out of scope. Thoughts, @jtf621 ?

**Comment by lemanal** [comment]
btw I looked into this. the DPS tool links into county assessor which doesn't have a record under that parcel ID. I'm not even sure that my geocoder suggestion would even be possible.

**Comment by jtf621** [comment]
Current behavior returns an alert "Geocode was not successful for the following reason: ZERO_RESULTS"
I agree that now that the user gets an error instead of the wrong address, the issue is fixed.

@lemanal I would close as fixed.
