### ISSUE TITLE
Update school profile email template

### ISSUE THREAD

**Issue by jtf621** [codefordurham/school-navigator#282]

**Comment by lemanal** [comment]
Dear [Principal name],
Following the recent presentation by Chrissy Deal about School Navigator at your May 3rd meeting, we are writing to request your help.  In partnership with Durham Public Schools, the PTA Council, and Durham parents, we at Code for Durham are creating a resource to help families understand the city's public school landscape.  The site will help families identify their zoned schools, view all public schools relative to their location, and access detailed and consistent information about each school. 
 
In order to create a great profile for [school name], we are requesting your help.  We ask that you and your team complete the survey below by [date] so we can include your school's completed profile on the site.  Please see below for the survey link and instructions. 
 
Email <sarah's email> if you have any questions. We know you are very busy and greatly appreciate you making time to complete this survey.  Many thanks in advance for your help! 
 
Sincerely,
School Navigator Team
