### ISSUE TITLE
School zone discrepancy

### ISSUE THREAD

**Issue by copelco** [codefordurham/school-navigator#73]
Searching for 1823 Umstead Rd on the [official tool](http://gisweb.durhamnc.gov/durhammaps/DPS/viewer/index.html) returns these extra results that our [navigator](https://schools.codefordurham.com/#/location/36.077959/-78.947226/) doesn't show:

* Eno Valley (elementary)
* The School for Creative Studies (middle year-round)

At first glance, it appears that some of the district shapes don't match.

**Comment by gghezzo** [comment]
I have the same issue. I am at 2403 Englewood Ave and currently evaluating middle schools for my son. I know I have 8 (I think) options and the Navigator only gives me 4. Let me know if there is more I can provide to debug the issue.

**Comment by lemanal** [comment]
@gghezzo Could you please let me know which schools you're seeing and which ones you're expecting to see (and why for each)?

**Comment by jtf621** [comment]
@lemanal, I have reviewed the official tool and the current production navigator and 
- for the @gghezzo issue for 2403 Englewood Ave, all the schools appear in navigator
- for @copelco issue for 1823 Umstead Rd, Sandy Ridge does show in options, but Eno Valley does not show.  This is because Eno Valley is the "Traditional Option" and the model/api/load_schools.py does not  capture this information.
